/**
 * TODO: This is pretty poorly organized. Would this be better used as a large single object?
 */

export const EmojiAnimals = {
  monkey: '🐒',
  dog: '🐕',
  gorilla: '🦍',
  poodle: '🐩',
  cat: '🐈',
  tiger: '🐅',
  horse: '🐎',
  deer: '🦌',
  cow: '🐄',
  ox: '🐂',
  pig: '🐖',
  ram: '🐏',
  goat: '🐐',
  camel: '🐪',
  elephant: '🐘',
  rhino: '🦏',
  hippo: '🦛',
  mouse: '🐁',
  rat: '🐀',
  rabbit: '🐇',
  hedgehog: '🦔',
  bat: '🦇',
  otter: '🦦',
  skunk: '🦨',
  kangaroo: '🦘',
  badger: '🦡',
  turkey: '🦃',
  rooster: '🐓',
  chick: '🐤',
  bird: '🐦',
  penguin: '🐧',
  eagle: '🦅',
  duck: '🦆',
  swan: '🦢',
  owl: '🦉',
  flamingo: '🦩',
  parrot: '🦜',
  peacock: '🦚',
  crocodile: '🐊',
  turtle: '🐢',
  lizard: '🦎',
  snacke: '🐍',
  dragon: '🐉',
  trex: '🦖',
  whale: '🐋',
  dolphin: '🐬',
  fish: '🐟',
  tropicalFish: '🐠',
  blowfish: '🐡',
  shark: '🦈',
  octopus: '🐙',
  snail: '🐌',
  butterfly: '🦋',
  bug: '🐛',
  ant: '🐜',
  honeybee: '🐝',
  ladybug: '🐞',
  cricket: '🦗',
  spider: '🕷',
  scorpion: '🦂',
  mosquito: '🦟',
  microbe: '🦠',
};

export const EmojiFood = {
  grapes: '🍇',
  melon: '🍈',
  water_melon: '🍉',
  tangerine: '🍊',
  lime: '🍋',
  banana: '🍌',
  pineapple: '🍍',
  mango: '🥭',
  red_apple: '🍎',
  green_apple: '🍏',
  pear: '🍐',
  peach: '🍑',
  cherries: '🍒',
  strawberries: '🍓',
  kiwi_fruit: '🥝',
  tomato: '🍅',
  coconut: '🥥',
  avocado: '🥑',
  eggplant: '🍆',
  potato: '🥔',
  carrot: '🥕',
  corn: '🌽',
  pepper: '🌶',
  cucumber: '🥒',
  leafy_green: '🥬',
  broccoli: '🥦',
  garlic: '🧄',
  onion: '🧅',
  mushroom: '🍄',
  peanuts: '🥜',
  chestnut: '🌰',
  bread: '🍞',
  croissant: '🥐',
  baguette_bread: '🥖',
  pretzel: '🥨',
  bagel: '🥯',
  pancake: '🥞',
  waffle: '🧇',
  cheese_wedge: '🧀',
  meat_with_bone: '🍖',
  poultry_leg: '🍗',
  cut_of_meat: '🥩',
  bacon: '🥓',
  hamburger: '🍔',
  french_fries: '🍟',
  pizza: '🍕',
  hot_dog: '🌭',
  sandwich: '🥪',
  taco: '🌮',
  burrito: '🌯',
  stuffed_flatbread: '🥙',
  falafel: '🧆',
  egg: '🥚',
  cooking: '🍳',
  shallow_pan_of_food: '🥘',
  pot_of_food: '🍲',
  bowl_with_food: '🥣',
  green_salad: '🥗',
  popcorn: '🍿',
  butter: '🧈',
  salt: '🧂',
  canned_food: '🥫',
  bento_box: '🍱',
  rice_cracker: '🍘',
  rice_ball: '🍙',
  cooked_rice: '🍚',
  curry_rice: '🍛',
  steaming_bowl: '🍜',
  spaghetti: '🍝',
  roasted_sweet_potato: '🍠',
  oden: '🍢',
  sushi: '🍣',
  fried_shrimp: '🍤',
  fish_cake_with_swiri: '🍥',
  moon_cake: '🥮',
  dango: '🍡',
  dumpling: '🥟',
  fortune_cookie: '🥠',
  take_out_box: '🥡',
  crab: '🦀',
  lobster: '🦞',
  shrimp: '🦐',
  squid: '🦑',
  oyster: '🦪',
  ice_cream: '🍨',
  shaved_ice_cream: '🍧',
  soft_ice_cream: '🍦',
  doughnut: '🍩',
  cookie: '🍪',
  birthday_cake: '🎂',
  short_cake: '🍰',
  cup_cake: '🧁',
  pie: '🥧',
  chocoloate: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  custard: '🍮',
  honey_pot: '🍯',
  baby_bottle: '🍼',
  glass_of_milk: '🥛',
  hot_beverage: '☕',
  teacup_without_handle: '🍵',
  sake: '🍶',
  bottle_with_poppin_cork: '🍾',
  wine_glass: '🍷',
  cocktail_glass: '🍸',
  tropical_drink: '🍹',
  beer_mug: '🍺',
  clinking_beer_mug: '🍻',
  clinking_glasses: '🥂',
  tumbler_glass: '🥃',
  cup_with_strawberry: '🥤',
  beverage_box: '🧃',
  mate: '🧉',
  ice: '🧊',
};

export const EmojiReactions = {
  kiss: '💋',
  love_letter: '💌',
  heart_with_arrow: '💘',
  heart_with_ribbon: '💝',
  sparking_heart: '💖',
  growing_heart: '💗',
  beating_heart: '💓',
  revolving_heart: '💞',
  two_hearts: '💕',
  heart_decoration: '💟',
  heart_exclamation: '❣',
  broken_heart: '💔',
  red_heart: '❤',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  brown_heart: '🤎',
  black_heart: '🖤',
  white_heart: '🤍',
  rainbow: '🌈',
  hundred: '💯',
  anger: '💢',
  collision: '💥',
  sparkles: '✨',
  baloon: '🎈',
  party_popper: '🎉',
  dizzy: '💫',
  sweat_droplets: '💦',
  dashing_away: '💨',
  hole: '🕳',
  bomb: '💣',
  left_speech_bubble: '🗨️',
  anger_bubble: '🗯️',
  thought_baloon: '💭',
  speech_baloon: '💬',
  zzz: '💤',
  red_question_mark: '❓',
  white_question_mark: '❔',
  red_exclamation_mark: '❗',
  white_exclamation_mark: '❕',
};

export const EmojiMasks = {
  pile_of_poo: '💩',
  clown: '🤡',
  ogre: '👹',
  goblin: '👺',
  ghost: '👻',
  alien: '👽',
  alien_monster: '👾',
  robot: '🤖',
};

export const EmojiFaces = {
  slightly_smiling_face: '🙂',
  smiling_face: '😀',
  smiling_face_with_big_eyes: '😃',
  grinning_face_with_smiling_eyes: '😄',
  beaming_face_with_smiling_eyes: '😁',
  smiling_face_with_tears: '😅',
  grinning_face: '😆',
  rolling_on_the_floor_laughing: '🤣',
  lauging_with_tears: '😂',
  upside_down_face: '🙃',
  winking_face: '😉',
  smiling_face_with_smiling_eyes: '😊',
  smiling_face_with_halo: '😇',
  smiling_face_with_sunglasses: '😎',
  nerdy_face: '🤓',
  face_with_monocle: '🧐',
  partying_face: '🥳',

  smiling_face_with_hearts: '🥰',
  smiling_face_with_heart_eyes: '😍',
  starStruck: '🤩',
  face_blowing_kiss: '😘',
  kissing_face: '😗',
  kissing_face_with_closed_eyes: '😚',
  kissng_face_with_smiling_eyes: '😙',

  yummy_face: '😋',
  face_with_tongue: '😛',
  winking_face_with_tongue: '😜',
  zanny_face: '🤪',
  squinting_face_with_tongue: '😝',
  money_face_with_money_tongue: '🤑',

  hugs: '🤗',
  face_with_hand_in_mouth: '🤭',
  shushing_face: '🤫',
  thinkin_face: '🤔',

  neutral_face: '😐',
  zipped_mouth: '🤐',
  face_with_raised_eyebrow: '🤨',
  expressionless_face: '😑',
  face_with_no_mouth: '😶',
  smirking_face: '😏',
  unamused_face: '😒',
  face_with_rolling_eyes: '🙄',
  grimacing_face: '😬',
  face_exhailing: '😮‍💨',
  lying_face: '🤥',

  sleepy_face: '😪',
  sleeping_face: '😴',
  relieved_face: '😌',
  pensive_face: '😔',
  drooling_face: '🤤',

  face_with_mask: '😷',
  face_with_thermometer: '🤒',
  face_with_bandage: '🤕',
  nauseous_face: '🤢',
  vomiting_face: '🤮',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  face_with_crossedOut_face: '😵',
  face_with_exploding_head: '🤯',

  confused_face: '😕',
  worried_face: '😟',
  slightly_frowning_face: '🙁',
  frowning_face: '☹',
  face_with_open_mouth: '😮',
  hushed_face: '😯',
  astonished_face: '😲',
  flushed_face: '😳',
  begging_face: '🥺',
  frowning_face_with_open_mouth: '😦',
  angushed_face: '😧',
  fearful_face: '😨',
  anxious_face_with_sweat: '😰',
  sad_but_relieved_face: '😥',
  crying_face: '😢',
  loudly_crying_face: '😭',
  screaming_face: '😱',
  confounded_face: '😖',
  persevering_face: '😣',
  disapointed_face: '😞',
  downcast_face_with_sweat: '😓',
  weary_face: '😩',
  tired_face: '😫',
  yawning_face: '🥱',

  face_with_steam: '😤',
  pouting_face: '😡',
  angry_face: '😠',
  face_with_symbols_on_mouth: '🤬',
  smiling_face_with_horns: '😈',
  angry_face_with_horns: '👿',
  skull: '💀',
  skull_and_crossBone: '☠️',
};

export const EmojiPrizes = {
  red_envelope: '🧧',
  ribbon: '🎀',
  wrapped_gift: '🎁',
  reminder_ribbon: '🎗️',
  admission_ticket: '🎟️',
  ticket: '🎫',
  military_medal: '🎖️',
  trophy: '🏆',
  sports_medal: '🏅',
  gold_medal: '🥇',
  silver_medal: '🥈',
  bronze_medal: '🥉',
  money_bag: '💰',
  yen_banknote: '💴',
  dollar_banknote: '💵',
  euro_banknote: '💶',
  pound_banknote: '💷',
  money_with_wings: '💸',
  credit_card: '💳',
};

export const EmojiAudio = {
  muted_speaker: '🔇',
  low_volume_speaker: '🔈',
  mid_volume_speaker: '🔉',
  high_volume_speaker: '🔊',
  loudspeaker: '📢',
  bell: '🔔',
  bell_with_slash: '🔕',
};

export const EmojiFlags = {
  chequered_flag: '🏁',
  triangular_flag: '🚩',
  crossed_flag: '🎌',
  black_flag: '🏴',
  pirate_flag: '️🏴‍☠',
};

export const EmojiShapes = {
  red_circle: '🔴',
  orange_circle: '🟠',
  yellow_circle: '🟡',
  green_circle: '🟢',
  blue_circle: '🔵',
  purple_circle: '🟣',
  brown_circle: '🟤',
  black_circle: '⚫',
  white_circle: '⚪',
  red_square: '🟥',
  orange_square: '🟧',
  yellow_square: '🟨',
  green_square: '🟩',
  blue_square: '🟦',
  purple_square: '🟪',
  brown_square: '🟫',
  black_square: '⬛',
  white_square: '⬜',
  large_orange_diamond: '🔶',
  large_blue_diamond: '🔷',
  small_orange_diamond: '🔸',
  small_blue_diamond: '🔹',
  red_triangle_pointed_up: '🔺',
  red_triangle_pointed_down: '🔻',
  diamond_with_a_dot: '💠',
  radio_button: '🔘',
  white_square_button: '🔳',
  black_square_button: '🔲',
};

export const EmojiTools = {
  hammer: '🔨',
  axe: '🪓',
  pick: '⛏️',
  dagger: '🗡️',
  // 🪒 Razor
  cross_swords: '⚔️',
  trident: '🔱',
  water_gun: '🔫',
  bow_and_arrow: '🏹',
  scissors: '✂️',
  shield: '🛡️',
  wrench: '🔧',
  clamp: '🗜️',
  balance_scale: '⚖️',
  white_cane: '🦯',
  link: '🔗',
  chains: '⛓️',
  toolbox: '🧰',
  magnet: '🧲',
  firecracker: '🧨',
  //   🎆 Fireworks
  // 🎇 Sparkler
};

export const EmojiMisc = {
  bullseye: '🎯',
  teddy_bear: '🧸',
  game_die: '🎲',
  puzzle_piece: '🧩',
  // ♟️ Chess Pawn
  //   🔑 Key
  // 🗝️ Old Key
  // 🗿 Moai
  //   🪐 Ringed Planet
  // 🌠 Shooting Star
  // 🌌 Milky Way
  //   🌀 Cyclone
  // ♠️ Spade Suit
  // ♥️ Heart Suit
  // ♦️ Diamond Suit
  // ♣️ Club Suit
  // 🃏 Joker
  // 🀄 Mahjong Red Dragon
  // 🎴 Flower Playing Cards
};

export const EmojiBuildings = {
  stadium: '️🏟️',
  classical_building: '️🏛️',
  building_construction: '️🏗️',
  houses: '️🏘️',
  derelict_house: '️🏚️',
  house: '🏠',
  house_with_garden: '🏡',
  office_building: '🏢',
  japanese_post_office: '🏣',
  post_office: '🏤',
  hospital: '🏥',
  bank: '🏦',
  hotel: '🏨',
  love_hotel: '🏩',
  convenience_store: '🏪',
  school: '🏫',
  department_store: '🏬',
  factory: '🏭',
  japanese_castle: '🏯',
  castle: '🏰',
  wedding: '💒',
  tokyo_tower: '🗼',
  statue_of_liberty: '🗽',
  church: '⛪',
  mosque: '🕌',
  hindu_temple: '🛕',
  synagogue: '🕍',
  shinto_shrine: '️⛩️',
  kaaba: '🕋',
  fountain: '⛲',
  tent: '⛺',
  foggy: '🌁',
  night_with_stars: '🌃',
  cityscape: '️🏙️',
  sunrise_over_mountains: '🌄',
  sunrise: '🌅',
  cityscape_at_dusk: '🌆',
  sunset: '🌇',
  bridge_at_night: '🌉',
};

export const EmojiVehicle = {
  carousel_horse: '🎠',
  ferris_wheel: '🎡',
  roller_coaster: '🎢',
  locomotive: '🚂',
  railway_car: '🚃',
  highSpeed_train: '🚄',
  bullet_train: '🚅',
  train: '🚆',
  metro: '🚇',
  light_rail: '🚈',
  station: '🚉',
  tram: '🚊',
  monorail: '🚝',
  mountain_railway: '🚞',
  tram_car: '🚋',
  bus: '🚌',
  oncoming_bus: '🚍',
  trolleybus: '🚎',
  minibus: '🚐',
  ambulance: '🚑',
  fire_engine: '🚒',
  police_car: '🚓',
  oncoming_police_car: '🚔',
  taxi: '🚕',
  oncoming_taxi: '🚖',
  automobile: '🚗',
  oncoming_automobile: '🚘',
  sport_utility_vehicle: '🚙',
  delivery_truck: '🚚',
  articulated_lorry: '🚛',
  tractor: '🚜',
  racing_car: '️🏎️',
  motorcycle: '️🏍️',
  motor_scooter: '🛵',
  auto_rickshaw: '🛺',
  bicycle: '🚲',
  kick_scooter: '🛴',
  bus_stop: '🚏',
  motorway: '️🛣️',
  railway_track: '️🛤️',
  fuel_pump: '⛽',
  police_car_light: '🚨',
  horizontal_traffic_light: '🚥',
  vertical_traffic_light: '🚦',
  construction: '🚧',
  anchor: '⚓',
  sailboat: '⛵',
  speedboat: '🚤',
  passenger_ship: '️🛳️',
  ferry: '️⛴️',
  motor_boat: '️🛥️',
  ship: '🚢',
  airplane: '️✈️',
  small_airplane: '️🛩️',
  airplane_departure: '🛫',
  airplane_arrival: '🛬',
  parachute: '🪂',
  seat: '💺',
  helicopter: '🚁',
  suspension_railway: '🚟',
  mountain_cableway: '🚠',
  aerial_tramway: '🚡',
  satellite: '️🛰️',
  rocket: '🚀',
  flying_saucer: '🛸',
};
