import { Emoji } from './Emoji';

export type MemoryGame = {
  sets: number;
  emojiPerSet: number;
  emojis: Emoji[];
  foundSets: Emoji[];
};

export const MemoryEmojis = [
  {
    code: ['U+1F600'],
    icon: '😀',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face',
  },
  {
    code: ['U+1F603'],
    icon: '😃',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with big eyes',
  },
  {
    code: ['U+1F604'],
    icon: '😄',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with smiling eyes',
  },
  {
    code: ['U+1F601'],
    icon: '😁',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'beaming face with smiling eyes',
  },
  {
    code: ['U+1F606'],
    icon: '😆',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning squinting face',
  },
  {
    code: ['U+1F605'],
    icon: '😅',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with sweat',
  },
  {
    code: ['U+1F923'],
    icon: '🤣',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'rolling on the floor laughing',
  },
  {
    code: ['U+1F602'],
    icon: '😂',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'face with tears of joy',
  },
  {
    code: ['U+1F642'],
    icon: '🙂',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'slightly smiling face',
  },
  {
    code: ['U+1F643'],
    icon: '🙃',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'upside-down face',
  },
  {
    code: ['U+1F609'],
    icon: '😉',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'winking face',
  },
  {
    code: ['U+1F60A'],
    icon: '😊',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'smiling face with smiling eyes',
  },
  {
    code: ['U+1F607'],
    icon: '😇',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'smiling face with halo',
  },
  {
    code: ['U+1F970'],
    icon: '🥰',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'smiling face with hearts',
  },
  {
    code: ['U+1F60D'],
    icon: '😍',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'smiling face with heart-eyes',
  },
  {
    code: ['U+1F929'],
    icon: '🤩',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'star-struck',
  },
  {
    code: ['U+1F618'],
    icon: '😘',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'face blowing a kiss',
  },
  {
    code: ['U+1F617'],
    icon: '😗',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face',
  },
  {
    code: ['U+1F61A'],
    icon: '😚',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face with closed eyes',
  },
  {
    code: ['U+1F619'],
    icon: '😙',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face with smiling eyes',
  },
  {
    code: ['U+1F600'],
    icon: '🙂',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face',
  },
  {
    code: ['U+1F600'],
    icon: '😀',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face',
  },
  {
    code: ['U+1F603'],
    icon: '😃',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with big eyes',
  },
  {
    code: ['U+1F604'],
    icon: '😄',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with smiling eyes',
  },
  {
    code: ['U+1F601'],
    icon: '😁',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'beaming face with smiling eyes',
  },
  {
    code: ['U+1F606'],
    icon: '😆',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning squinting face',
  },
  {
    code: ['U+1F605'],
    icon: '😅',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'grinning face with sweat',
  },
  {
    code: ['U+1F923'],
    icon: '🤣',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'rolling on the floor laughing',
  },
  {
    code: ['U+1F602'],
    icon: '😂',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'face with tears of joy',
  },
  {
    code: ['U+1F642'],
    icon: '🙂',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'slightly smiling face',
  },
  {
    code: ['U+1F643'],
    icon: '🙃',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'upside-down face',
  },
  //🫠	melting face
  {
    code: ['U+1F609'],
    icon: '😉',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'winking face',
  },
  {
    code: ['U+1F60A'],
    icon: '😊',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'smiling face with smiling eyes',
  },
  {
    code: ['U+1F607'],
    icon: '😇',
    parent_cat: 'face',
    child_cat: 'smiling',
    short_name: 'smiling face with halo',
  },
  //face-affection

  {
    code: ['U+1F970'],
    icon: '🥰',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'smiling face with hearts',
  },
  {
    code: ['U+1F60D'],
    icon: '😍',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'smiling face with heart-eyes',
  },
  {
    code: ['U+1F929'],
    icon: '🤩',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'star-struck',
  },
  {
    code: ['U+1F618'],
    icon: '😘',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'face blowing a kiss',
  },
  {
    code: ['U+1F617'],
    icon: '😗',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face',
  },
  {
    code: ['U+1F61A'],
    icon: '😚',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face with closed eyes',
  },
  {
    code: ['U+1F619'],
    icon: '😙',
    parent_cat: 'face',
    child_cat: 'affection',
    short_name: 'kissing face with smiling eyes',
  },
  //face-tongue

  {
    code: ['U+1F60B'],
    icon: '😋',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'face savoring food',
  },
  {
    code: ['U+1F61B'],
    icon: '😛',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'face with tongue',
  },
  {
    code: ['U+1F61C'],
    icon: '😜',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'winking face with tongue',
  },
  {
    code: ['U+1F92A'],
    icon: '🤪',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'zany face',
  },
  {
    code: ['U+1F61D'],
    icon: '😝',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'squinting face with tongue',
  },
  {
    code: ['U+1F911'],
    icon: '🤑',
    parent_cat: 'face',
    child_cat: 'tongue',
    short_name: 'money-mouth face',
  },
  //face-hand

  {
    code: ['U+1F917'],
    icon: '🤗',
    parent_cat: 'face',
    child_cat: 'hand',
    short_name: 'smiling face with open hands',
  },
  {
    code: ['U+1F92D'],
    icon: '🤭',
    parent_cat: 'face',
    child_cat: 'hand',
    short_name: 'face with hand over mouth',
  },
  // 🫢	face with open eyes and hand over mouth
  // 🫣	face with peeking eye
  {
    code: ['U+1F92B'],
    icon: '🤫',
    parent_cat: 'face',
    child_cat: 'hand',
    short_name: 'shushing face',
  },
  {
    code: ['U+1F914'],
    icon: '🤔',
    parent_cat: 'face',
    child_cat: 'hand',
    short_name: 'thinking face',
  },
  // 🫡	saluting face
  // face-neutral-skeptical

  {
    code: ['U+1F910'],
    icon: '🤐',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'zipper-mouth face',
  },
  {
    code: ['U+1F928'],
    icon: '🤨',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'face with raised eyebrow',
  },
  {
    code: ['U+1F610'],
    icon: '😐',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'neutral face',
  },
  {
    code: ['U+1F611'],
    icon: '😑',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'expressionless face',
  },
  {
    code: ['U+1F636'],
    icon: '😶',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'face without mouth',
  },
  {
    code: ['U+1F60F'],
    icon: '😏',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'smirking face',
  },
  {
    code: ['U+1F612'],
    icon: '😒',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'unamused face',
  },
  {
    code: ['U+1F644'],
    icon: '🙄',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'face with rolling eyes',
  },
  {
    code: ['U+1F62C'],
    icon: '😬',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'grimacing face',
  },
  {
    code: ['U+1F925'],
    icon: '🤥',
    parent_cat: 'face',
    child_cat: 'neutral-skeptical',
    short_name: 'lying face',
  },
  //face-sleepy

  {
    code: ['U+1F60C'],
    icon: '😌',
    parent_cat: 'face',
    child_cat: 'sleepy',
    short_name: 'relieved face',
  },
  {
    code: ['U+1F614'],
    icon: '😔',
    parent_cat: 'face',
    child_cat: 'sleepy',
    short_name: 'pensive face',
  },
  {
    code: ['U+1F62A'],
    icon: '😪',
    parent_cat: 'face',
    child_cat: 'sleepy',
    short_name: 'sleepy face',
  },
  {
    code: ['U+1F924'],
    icon: '🤤',
    parent_cat: 'face',
    child_cat: 'sleepy',
    short_name: 'drooling face',
  },
  {
    code: ['U+1F634'],
    icon: '😴',
    parent_cat: 'face',
    child_cat: 'sleepy',
    short_name: 'sleeping face',
  },
  //face-unwell

  {
    code: ['U+1F637'],
    icon: '😷',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'face with medical mask',
  },
  {
    code: ['U+1F912'],
    icon: '🤒',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'face with thermometer',
  },
  {
    code: ['U+1F915'],
    icon: '🤕',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'face with head-bandage',
  },
  {
    code: ['U+1F922'],
    icon: '🤢',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'nauseated face',
  },
  {
    code: ['U+1F92E'],
    icon: '🤮',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'face vomiting',
  },
  {
    code: ['U+1F927'],
    icon: '🤧',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'sneezing face',
  },
  {
    code: ['U+1F975'],
    icon: '🥵',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'hot face',
  },
  {
    code: ['U+1F976'],
    icon: '🥶',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'cold face',
  },
  {
    code: ['U+1F974'],
    icon: '🥴',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'woozy face',
  },
  {
    code: ['U+1F635'],
    icon: '😵',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'face with crossed-out eyes',
  },
  {
    code: ['U+1F92F'],
    icon: '🤯',
    parent_cat: 'face',
    child_cat: 'unwell',
    short_name: 'exploding head',
  },
  //face-hat

  {
    code: ['U+1F920'],
    icon: '🤠',
    parent_cat: 'face',
    child_cat: 'hat',
    short_name: 'cowboy hat face',
  },
  {
    code: ['U+1F973'],
    icon: '🥳',
    parent_cat: 'face',
    child_cat: 'hat',
    short_name: 'partying face',
  },
  //face-glasses

  {
    code: ['U+1F60E'],
    icon: '😎',
    parent_cat: 'face',
    child_cat: 'glasses',
    short_name: 'smiling face with sunglasses',
  },
  {
    code: ['U+1F913'],
    icon: '🤓',
    parent_cat: 'face',
    child_cat: 'glasses',
    short_name: 'nerd face',
  },
  {
    code: ['U+1F9D0'],
    icon: '🧐',
    parent_cat: 'face',
    child_cat: 'glasses',
    short_name: 'face with monocle',
  },
  //face-concerned

  {
    code: ['U+1F615'],
    icon: '😕',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'confused face',
  },
  //🫤	face with diagonal mouth
  {
    code: ['U+1F61F'],
    icon: '😟',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'worried face',
  },
  {
    code: ['U+1F641'],
    icon: '🙁',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'slightly frowning face',
  },
  {
    code: ['U+1F62E'],
    icon: '😮',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'face with open mouth',
  },
  {
    code: ['U+1F62F'],
    icon: '😯',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'hushed face',
  },
  {
    code: ['U+1F632'],
    icon: '😲',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'astonished face',
  },
  {
    code: ['U+1F633'],
    icon: '😳',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'flushed face',
  },
  {
    code: ['U+1F97A'],
    icon: '🥺',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'pleading face',
  },
  //🥹	face holding back tears
  {
    code: ['U+1F626'],
    icon: '😦',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'frowning face with open mouth',
  },
  {
    code: ['U+1F627'],
    icon: '😧',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'anguished face',
  },
  {
    code: ['U+1F628'],
    icon: '😨',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'fearful face',
  },
  {
    code: ['U+1F630'],
    icon: '😰',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'anxious face with sweat',
  },
  {
    code: ['U+1F625'],
    icon: '😥',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'sad but relieved face',
  },
  {
    code: ['U+1F622'],
    icon: '😢',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'crying face',
  },
  {
    code: ['U+1F62D'],
    icon: '😭',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'loudly crying face',
  },
  {
    code: ['U+1F631'],
    icon: '😱',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'face screaming in fear',
  },
  {
    code: ['U+1F616'],
    icon: '😖',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'confounded face',
  },

  {
    code: ['U+1F623'],
    icon: '😣',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'persevering face',
  },
  {
    code: ['U+1F61E'],
    icon: '😞',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'disappointed face',
  },
  {
    code: ['U+1F613'],
    icon: '😓',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'downcast face with sweat',
  },
  {
    code: ['U+1F629'],
    icon: '😩',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'weary face',
  },
  {
    code: ['U+1F62B'],
    icon: '😫',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'tired face',
  },
  {
    code: ['U+1F971'],
    icon: '🥱',
    parent_cat: 'face',
    child_cat: 'concerned',
    short_name: 'yawning face',
  },
  //face-negative

  {
    code: ['U+1F624'],
    icon: '😤',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'face with steam from nose',
  },
  {
    code: ['U+1F621'],
    icon: '😡',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'pouting face',
  },
  {
    code: ['U+1F620'],
    icon: '😠',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'angry face',
  },
  {
    code: ['U+1F92C'],
    icon: '🤬',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'face with symbols on mouth',
  },
  {
    code: ['U+1F608'],
    icon: '😈',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'smiling face with horns',
  },
  {
    code: ['U+1F47F'],
    icon: '👿',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'angry face with horns',
  },
  {
    code: ['U+1F480'],
    icon: '💀',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'skull',
  },
  {
    code: ['U+2620'],
    icon: '☠️',
    parent_cat: 'face',
    child_cat: 'negative',
    short_name: 'skull and crossbones',
  },
  //face-costume

  {
    code: ['U+1F4A9'],
    icon: '💩',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'pile of poo',
  },
  {
    code: ['U+1F921'],
    icon: '🤡',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'clown face',
  },
  {
    code: ['U+1F479'],
    icon: '👹',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'ogre',
  },
  {
    code: ['U+1F47A'],
    icon: '👺',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'goblin',
  },
  {
    code: ['U+1F47B'],
    icon: '👻',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'ghost',
  },
  {
    code: ['U+1F47D'],
    icon: '👽',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'alien',
  },
  {
    code: ['U+1F47E'],
    icon: '👾',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'alien monster',
  },
  {
    code: ['U+1F916'],
    icon: '🤖',
    parent_cat: 'face',
    child_cat: 'costume',
    short_name: 'robot',
  },
  //cat-face

  {
    code: ['U+1F63A'],
    icon: '😺',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'grinning cat',
  },
  {
    code: ['U+1F638'],
    icon: '😸',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'grinning cat with smiling eyes',
  },
  {
    code: ['U+1F639'],
    icon: '😹',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'cat with tears of joy',
  },
  {
    code: ['U+1F63B'],
    icon: '😻',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'smiling cat with heart-eyes',
  },
  {
    code: ['U+1F63C'],
    icon: '😼',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'cat with wry smile',
  },
  {
    code: ['U+1F63D'],
    icon: '😽',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'kissing cat',
  },
  {
    code: ['U+1F640'],
    icon: '🙀',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'weary cat',
  },
  {
    code: ['U+1F63F'],
    icon: '😿',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'crying cat',
  },
  {
    code: ['U+1F63E'],
    icon: '😾',
    parent_cat: 'face',
    child_cat: 'cat',
    short_name: 'pouting cat',
  },
  //monkey-face

  {
    code: ['U+1F648'],
    icon: '🙈',
    parent_cat: 'face',
    child_cat: 'monkey',
    short_name: 'see-no-evil monkey',
  },
  {
    code: ['U+1F649'],
    icon: '🙉',
    parent_cat: 'face',
    child_cat: 'monkey',
    short_name: 'hear-no-evil monkey',
  },
  {
    code: ['U+1F64A'],
    icon: '🙊',
    parent_cat: 'face',
    child_cat: 'monkey',
    short_name: 'speak-no-evil monkey',
  },
  //emotion

  {
    code: ['U+1F48B'],
    icon: '💋',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'kiss mark',
  },
  {
    code: ['U+1F48C'],
    icon: '💌',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'love letter',
  },
  {
    code: ['U+1F498'],
    icon: '💘',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'heart with arrow',
  },
  {
    code: ['U+1F49D'],
    icon: '💝',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'heart with ribbon',
  },
  {
    code: ['U+1F496'],
    icon: '💖',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'sparkling heart',
  },
  {
    code: ['U+1F497'],
    icon: '💗',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'growing heart',
  },
  {
    code: ['U+1F493'],
    icon: '💓',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'beating heart',
  },
  {
    code: ['U+1F49E'],
    icon: '💞',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'revolving hearts',
  },
  {
    code: ['U+1F495'],
    icon: '💕',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'two hearts',
  },
  {
    code: ['U+1F49F'],
    icon: '💟',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'heart decoration',
  },
  {
    code: ['U+2763'],
    icon: '❣',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'heart exclamation',
  },
  {
    code: ['U+1F494'],
    icon: '💔',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'broken heart',
  },
  {
    code: ['U+2764'],
    icon: '❤',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'red heart',
  },
  {
    code: ['U+1F9E1'],
    icon: '🧡',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'orange heart',
  },
  {
    code: ['U+1F49B'],
    icon: '💛',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'yellow heart',
  },
  {
    code: ['U+1F49A'],
    icon: '💚',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'green heart',
  },
  {
    code: ['U+1F499'],
    icon: '💙',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'blue heart',
  },
  {
    code: ['U+1F49C'],
    icon: '💜',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'purple heart',
  },

  {
    code: ['U+1F90E'],
    icon: '🤎',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'brown heart',
  },
  {
    code: ['U+1F5A4'],
    icon: '🖤',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'black heart',
  },
  {
    code: ['U+1F90D'],
    icon: '🤍',
    parent_cat: 'emotion',
    child_cat: 'heart',
    short_name: 'white heart',
  },

  {
    code: ['U+1F4AF'],
    icon: '💯',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'hundred points',
  },
  {
    code: ['U+1F4A2'],
    icon: '💢',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'anger symbol',
  },
  {
    code: ['U+1F4A5'],
    icon: '💥',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'collision',
  },
  {
    code: ['U+1F4AB'],
    icon: '💫',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'dizzy',
  },
  {
    code: ['U+1F4A6'],
    icon: '💦',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'sweat droplets',
  },
  {
    code: ['U+1F4A8'],
    icon: '💨',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'dashing away',
  },
  {
    code: ['U+1F573'],
    icon: '🕳',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'hole',
  },
  {
    code: ['U+1F4A3'],
    icon: '💣',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'bomb',
  },
  {
    code: ['U+1F4AC'],
    icon: '💬',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'speech balloon',
  },
  {
    code: [''],
    icon: '👁️‍🗨️',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'eye in speech bubble',
  },
  {
    code: ['U+1F5E8'],
    icon: '🗨',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'left speech bubble',
  },
  {
    code: ['U+1F5EF'],
    icon: '🗯',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'right anger bubble',
  },
  {
    code: ['U+1F4AD'],
    icon: '💭',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'thought balloon',
  },
  {
    code: ['U+1F4A4'],
    icon: '💤',
    parent_cat: 'emotion',
    child_cat: 'reaction',
    short_name: 'zzz',
  },
  // People & Body
  // hand-fingers-open

  {
    code: ['U+1F44B'],
    icon: '👋',
    parent_cat: 'hand',
    child_cat: 'fingers-open',
    short_name: 'waving hand',
  },
  {
    code: ['U+1F91A'],
    icon: '🤚',
    parent_cat: 'hand',
    child_cat: 'fingers-open',
    short_name: 'raised back of hand',
  },
  {
    code: ['U+1F590'],
    icon: '🖐️',
    parent_cat: 'hand',
    child_cat: 'fingers-open',
    short_name: 'hand with fingers splayed',
  },
  {
    code: ['U+270B'],
    icon: '✋',
    parent_cat: 'hand',
    child_cat: 'fingers-open',
    short_name: 'raised hand',
  },
  {
    code: ['U+1F596'],
    icon: '🖖',
    parent_cat: 'hand',
    child_cat: 'fingers-open',
    short_name: 'vulcan salute',
  },
  // 🫱	rightwards hand
  // 🫲	leftwards hand
  // 🫳	palm down hand
  // 🫴	palm up hand
  // hand-fingers-partial

  {
    code: ['U+1F44C'],
    icon: '👌',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'OK hand',
  },
  {
    code: ['U+1F90F'],
    icon: '🤏',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'pinching hand',
  },
  {
    code: ['U+270C'],
    icon: '✌️',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'victory hand',
  },
  {
    code: ['U+1F91E'],
    icon: '🤞',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'crossed fingers',
  },
  // 🫰	hand with index finger and thumb crossed
  {
    code: ['U+1F91F'],
    icon: '🤟',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'love-you gesture',
  },
  {
    code: ['U+1F918'],
    icon: '🤘',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'sign of the horns',
  },
  {
    code: ['U+1F919'],
    icon: '🤙',
    parent_cat: 'hand',
    child_cat: 'fingers-partial',
    short_name: 'call me hand',
  },
  // hand-single-finger

  {
    code: ['U+1F448'],
    icon: '👈',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'backhand index pointing left',
  },
  {
    code: ['U+1F449'],
    icon: '👉',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'backhand index pointing right',
  },
  {
    code: ['U+1F446'],
    icon: '👆',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'backhand index pointing up',
  },
  {
    code: ['U+1F595'],
    icon: '🖕',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'middle finger',
  },
  {
    code: ['U+1F447'],
    icon: '👇',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'backhand index pointing down',
  },
  {
    code: ['U+261D'],
    icon: '☝️',
    parent_cat: 'hand',
    child_cat: 'single-finger',
    short_name: 'index pointing up',
  },
  // 🫵	index pointing at the viewer
  // hand-fingers-closed

  {
    code: ['U+1F44D'],
    icon: '👍',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'thumbs up',
  },
  {
    code: ['U+1F44E'],
    icon: '👎',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'thumbs down',
  },
  {
    code: ['U+270A'],
    icon: '✊',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'raised fist',
  },
  {
    code: ['U+1F44A'],
    icon: '👊',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'oncoming fist',
  },
  {
    code: ['U+1F91B'],
    icon: '🤛',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'left-facing fist',
  },
  {
    code: ['U+1F91C'],
    icon: '🤜',
    parent_cat: 'hand',
    child_cat: 'fingers-closed',
    short_name: 'right-facing fist',
  },
  //hands

  {
    code: ['U+1F44F'],
    icon: '👏',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'clapping hands',
  },
  {
    code: ['U+1F64C'],
    icon: '🙌',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'raising hands',
  },
  //🫶	heart hands
  {
    code: ['U+1F450'],
    icon: '👐',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'open hands',
  },
  {
    code: ['U+1F932'],
    icon: '🤲',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'palms up together',
  },
  {
    code: ['U+1F91D'],
    icon: '🤝',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'handshake',
  },
  {
    code: ['U+1F64F'],
    icon: '🙏',
    parent_cat: 'hand',
    child_cat: 'hands',
    short_name: 'folded hands',
  },
  //hand-prop

  {
    code: ['U+270D'],
    icon: '✍️',
    parent_cat: 'hand',
    child_cat: 'prop',
    short_name: 'writing hand',
  },
  {
    code: ['U+1F485'],
    icon: '💅',
    parent_cat: 'hand',
    child_cat: 'prop',
    short_name: 'nail polish',
  },
  {
    code: ['U+1F933'],
    icon: '🤳',
    parent_cat: 'hand',
    child_cat: 'prop',
    short_name: 'selfie',
  },
  //body-parts

  {
    code: ['U+1F4AA'],
    icon: '💪',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'flexed biceps',
  },
  {
    code: ['U+1F9BE'],
    icon: '🦾',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'mechanical arm',
  },
  {
    code: ['U+1F9BF'],
    icon: '🦿',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'mechanical leg',
  },
  {
    code: ['U+1F9B5'],
    icon: '🦵',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'leg',
  },
  {
    code: ['U+1F9B6'],
    icon: '🦶',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'foot',
  },
  {
    code: ['U+1F442'],
    icon: '👂',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'ear',
  },
  {
    code: ['U+1F9BB'],
    icon: '🦻',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'ear with hearing aid',
  },
  {
    code: ['U+1F443'],
    icon: '👃',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'nose',
  },
  {
    code: ['U+1F9E0'],
    icon: '🧠',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'brain',
  },
  {
    code: ['U+1F9B7'],
    icon: '🦷',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'tooth',
  },
  {
    code: ['U+1F9B4'],
    icon: '🦴',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'bone',
  },
  {
    code: ['U+1F440'],
    icon: '👀',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'eyes',
  },
  {
    code: ['U+1F441'],
    icon: '👁️',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'eye',
  },
  {
    code: ['U+1F445'],
    icon: '👅',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'tongue',
  },
  {
    code: ['U+1F444'],
    icon: '👄',
    parent_cat: 'body',
    child_cat: 'parts',
    short_name: 'mouth',
  },
  // 🫦	biting lip
  // person

  {
    code: ['U+1F476'],
    icon: '👶',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'baby',
  },
  {
    code: ['U+1F9D2'],
    icon: '🧒',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'child',
  },
  {
    code: ['U+1F466'],
    icon: '👦',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'boy',
  },
  {
    code: ['U+1F467'],
    icon: '👧',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'girl',
  },
  {
    code: ['U+1F9D1'],
    icon: '🧑',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'people',
  },
  {
    code: ['U+1F471'],
    icon: '👱',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'person: blond hair',
  },
  {
    code: ['U+1F468'],
    icon: '👨',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man',
  },
  {
    code: ['U+1F9D4'],
    icon: '🧔',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'person: beard',
  },
  {
    code: [''],
    icon: '👨‍🦰',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man: red hair',
  },
  {
    code: [''],
    icon: '👨‍🦱',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man: curly hair',
  },
  {
    code: [''],
    icon: '👨‍🦳',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man: white hair',
  },
  {
    code: [''],
    icon: '👨‍🦲',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man: bald',
  },
  {
    code: ['U+1F469'],
    icon: '👩',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman',
  },
  {
    code: [''],
    icon: '👩‍🦰',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman: red hair',
  },
  {
    code: [''],
    icon: '👩‍🦱',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman: curly hair',
  },
  {
    code: [''],
    icon: '👩‍🦳',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman: white hair',
  },
  {
    code: [''],
    icon: '👩‍🦲',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman: bald',
  },
  {
    code: [''],
    icon: '👱‍♀️',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'woman: blond hair',
  },
  {
    code: [''],
    icon: '👱‍♂️',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'man: blond hair',
  },
  {
    code: ['U+1F9D3'],
    icon: '🧓',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'older person',
  },
  {
    code: ['U+1F474'],
    icon: '👴',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'old man',
  },
  {
    code: ['U+1F475'],
    icon: '👵',
    parent_cat: 'people',
    child_cat: 'face',
    short_name: 'old woman',
  },
  //person-gesture

  {
    code: ['U+1F64D'],
    icon: '🙍',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person frowning',
  },
  {
    code: [''],
    icon: '🙍‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man frowning',
  },
  {
    code: [''],
    icon: '🙍‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman frowning',
  },
  {
    code: ['U+1F64E'],
    icon: '🙎',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person pouting',
  },
  {
    code: [''],
    icon: '🙎‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man pouting',
  },
  {
    code: [''],
    icon: '🙎‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman pouting',
  },
  {
    code: ['U+1F645'],
    icon: '🙅',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person gesturing NO',
  },
  {
    code: [''],
    icon: '🙅‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man gesturing NO',
  },
  {
    code: [''],
    icon: '🙅‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman gesturing NO',
  },
  {
    code: ['U+1F646'],
    icon: '🙆',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person gesturing OK',
  },
  {
    code: [''],
    icon: '🙆‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man gesturing OK',
  },
  {
    code: [''],
    icon: '🙆‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman gesturing OK',
  },
  {
    code: ['U+1F481'],
    icon: '💁',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person tipping hand',
  },
  {
    code: [''],
    icon: '💁‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man tipping hand',
  },
  {
    code: [''],
    icon: '💁‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman tipping hand',
  },
  {
    code: ['U+1F64B'],
    icon: '🙋',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person raising hand',
  },
  {
    code: [''],
    icon: '🙋‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man raising hand',
  },
  {
    code: [''],
    icon: '🙋‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman raising hand',
  },
  {
    code: ['U+1F9CF'],
    icon: '🧏',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'deaf person',
  },
  {
    code: [''],
    icon: '🧏‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'deaf man',
  },
  {
    code: [''],
    icon: '🧏‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'deaf woman',
  },
  {
    code: ['U+1F647'],
    icon: '🙇',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person bowing',
  },
  {
    code: [''],
    icon: '🙇‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man bowing',
  },
  {
    code: [''],
    icon: '🙇‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman bowing',
  },
  {
    code: ['U+1F926'],
    icon: '🤦',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person facepalming',
  },
  {
    code: [''],
    icon: '🤦‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man facepalming',
  },
  {
    code: [''],
    icon: '🤦‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman facepalming',
  },
  {
    code: ['U+1F937'],
    icon: '🤷',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'person shrugging',
  },
  {
    code: [''],
    icon: '🤷‍♂️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'man shrugging',
  },
  {
    code: [''],
    icon: '🤷‍♀️',
    parent_cat: 'people',
    child_cat: 'gesture',
    short_name: 'woman shrugging',
  },
  {
    code: [''],
    icon: '👨‍⚕️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man health worker',
  },
  {
    code: [''],
    icon: '👩‍⚕️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman health worker',
  },
  {
    code: [''],
    icon: '👨‍🎓',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man student',
  },
  {
    code: [''],
    icon: '👩‍🎓',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman student',
  },
  {
    code: [''],
    icon: '👨‍🏫',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man teacher',
  },
  {
    code: [''],
    icon: '👩‍🏫',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman teacher',
  },
  {
    code: [''],
    icon: '👨‍⚖️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man judge',
  },
  {
    code: [''],
    icon: '👩‍⚖️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman judge',
  },
  {
    code: [''],
    icon: '👨‍🌾',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man farmer',
  },
  {
    code: [''],
    icon: '👩‍🌾',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman farmer',
  },
  {
    code: [''],
    icon: '👨‍🍳',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man cook',
  },
  {
    code: [''],
    icon: '👩‍🍳',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman cook',
  },
  {
    code: [''],
    icon: '👨‍🔧',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man mechanic',
  },

  {
    code: [''],
    icon: '👩‍🔧',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman mechanic',
  },
  {
    code: [''],
    icon: '👨‍🏭',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man factory worker',
  },
  {
    code: [''],
    icon: '👩‍🏭',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman factory worker',
  },
  {
    code: [''],
    icon: '👨‍💼',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man office worker',
  },
  {
    code: [''],
    icon: '👩‍💼',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman office worker',
  },
  {
    code: [''],
    icon: '👨‍🔬',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man scientist',
  },
  {
    code: [''],
    icon: '👩‍🔬',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman scientist',
  },
  {
    code: [''],
    icon: '👨‍💻',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man technologist',
  },
  {
    code: [''],
    icon: '👩‍💻',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman technologist',
  },
  {
    code: [''],
    icon: '👨‍🎤',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man singer',
  },
  {
    code: [''],
    icon: '👩‍🎤',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman singer',
  },
  {
    code: [''],
    icon: '👨‍🎨',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man artist',
  },
  {
    code: [''],
    icon: '👩‍🎨',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman artist',
  },
  {
    code: [''],
    icon: '👨‍✈️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man pilot',
  },
  {
    code: [''],
    icon: '👩‍✈️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman pilot',
  },
  {
    code: [''],
    icon: '👨‍🚀',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man astronaut',
  },
  {
    code: [''],
    icon: '👩‍🚀',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman astronaut',
  },
  {
    code: [''],
    icon: '👨‍🚒',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man firefighter',
  },
  {
    code: [''],
    icon: '👩‍🚒',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman firefighter',
  },
  {
    code: [''],
    icon: '👮',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'police officer',
  },
  {
    code: [''],
    icon: '👮‍♂️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man police officer',
  },
  {
    code: [''],
    icon: '👮‍♀️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman police officer',
  },
  {
    code: [''],
    icon: '🕵️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'detective',
  },
  {
    code: [''],
    icon: '🕵️‍♂️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man detective',
  },
  {
    code: [''],
    icon: '🕵️‍♀️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman detective',
  },
  {
    code: [''],
    icon: '💂',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'guard',
  },
  {
    code: [''],
    icon: '💂‍♂️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man guard',
  },
  {
    code: [''],
    icon: '💂‍♀️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman guard',
  },
  {
    code: [''],
    icon: '👷',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'construction worker',
  },
  {
    code: [''],
    icon: '👷‍♂️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man construction worker',
  },
  {
    code: [''],
    icon: '👷‍♀️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman construction worker',
  },
  //🫅	person with crown
  {
    code: [''],
    icon: '🤴',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'prince',
  },
  {
    code: [''],
    icon: '👸',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'princess',
  },
  {
    code: [''],
    icon: '👳',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'person wearing turban',
  },
  {
    code: [''],
    icon: '👳‍♂️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'man wearing turban',
  },
  {
    code: [''],
    icon: '👳‍♀️',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman wearing turban',
  },
  {
    code: [''],
    icon: '👲',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'person with skullcap',
  },
  {
    code: [''],
    icon: '🧕',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'woman with headscarf',
  },
  {
    code: [''],
    icon: '🤵',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'person in tuxedo',
  },
  {
    code: [''],
    icon: '👰',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'person with veil',
  },
  {
    code: [''],
    icon: '🤰',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'pregnant woman',
  },
  // 🫃	pregnant man
  // 🫄	pregnant person
  {
    code: [''],
    icon: '🤱',
    parent_cat: 'people',
    child_cat: 'role',
    short_name: 'breast-feeding',
  },
  // person-fantasy

  {
    code: [''],
    icon: '👼',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'baby angel',
  },
  {
    code: [''],
    icon: '🎅',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'Santa Claus',
  },
  {
    code: [''],
    icon: '🤶',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'Mrs. Claus',
  },
  {
    code: [''],
    icon: '🦸',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'superhero',
  },
  {
    code: [''],
    icon: '🦸‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man superhero',
  },
  {
    code: [''],
    icon: '🦸‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman superhero',
  },
  {
    code: [''],
    icon: '🦹',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'supervillain',
  },
  {
    code: [''],
    icon: '🦹‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man supervillain',
  },
  {
    code: [''],
    icon: '🦹‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman supervillain',
  },
  {
    code: [''],
    icon: '🧙',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'mage',
  },
  {
    code: [''],
    icon: '🧙‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man mage',
  },
  {
    code: [''],
    icon: '🧙‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman mage',
  },
  {
    code: [''],
    icon: '🧚',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'fairy',
  },
  {
    code: [''],
    icon: '🧚‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man fairy',
  },
  {
    code: [''],
    icon: '🧚‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman fairy',
  },
  {
    code: [''],
    icon: '🧛',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'vampire',
  },
  {
    code: [''],
    icon: '🧛‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man vampire',
  },
  {
    code: [''],
    icon: '🧛‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman vampire',
  },
  {
    code: [''],
    icon: '🧜',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'merperson',
  },
  {
    code: [''],
    icon: '🧜‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'merman',
  },
  {
    code: [''],
    icon: '🧜‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'mermaid',
  },
  {
    code: [''],
    icon: '🧝',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'elf',
  },
  {
    code: [''],
    icon: '🧝‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man elf',
  },
  {
    code: [''],
    icon: '🧝‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman elf',
  },
  {
    code: [''],
    icon: '🧞',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'genie',
  },
  {
    code: [''],
    icon: '🧞‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man genie',
  },
  {
    code: [''],
    icon: '🧞‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman genie',
  },
  {
    code: [''],
    icon: '🧟',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'zombie',
  },
  {
    code: [''],
    icon: '🧟‍♂️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'man zombie',
  },
  {
    code: [''],
    icon: '🧟‍♀️',
    parent_cat: 'people',
    child_cat: 'fantasy',
    short_name: 'woman zombie',
  },
  {
    code: [''],
    icon: '💆',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person getting massage',
  },
  {
    code: [''],
    icon: '💆‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man getting massage',
  },
  {
    code: [''],
    icon: '💆‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman getting massage',
  },
  {
    code: [''],
    icon: '💇',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person getting haircut',
  },
  {
    code: [''],
    icon: '💇‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man getting haircut',
  },
  {
    code: [''],
    icon: '💇‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman getting haircut',
  },
  {
    code: [''],
    icon: '🚶',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person walking',
  },
  {
    code: [''],
    icon: '🚶‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man walking',
  },
  {
    code: [''],
    icon: '🚶‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman walking',
  },
  {
    code: [''],
    icon: '🧍',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person standing',
  },
  {
    code: [''],
    icon: '🧍‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man standing',
  },
  {
    code: [''],
    icon: '🧍‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman standing',
  },
  {
    code: [''],
    icon: '🧎',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person kneeling',
  },

  {
    code: [''],
    icon: '👩‍🦯',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman with white cane',
  },
  {
    code: [''],
    icon: '👩‍🦼',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman in motorized wheelchair',
  },
  {
    code: [''],
    icon: '👨‍🦽',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man in manual wheelchair',
  },
  {
    code: [''],
    icon: '🏃',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person running',
  },
  {
    code: [''],
    icon: '💃',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman dancing',
  },
  {
    code: [''],
    icon: '🕺',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man dancing',
  },
  {
    code: [''],
    icon: '🕴️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'person in suit levitating',
  },
  {
    code: [''],
    icon: '👯‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'men with bunny ears',
  },
  {
    code: [''],
    icon: '👯‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'women with bunny ears',
  },
  {
    code: [''],
    icon: '🧖‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man in steamy room',
  },
  {
    code: [''],
    icon: '🧖‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman in steamy room',
  },
  {
    code: [''],
    icon: '🧗‍♂️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'man climbing',
  },
  {
    code: [''],
    icon: '🧗‍♀️',
    parent_cat: 'people',
    child_cat: 'activity',
    short_name: 'woman climbing',
  },
  {
    code: [''],
    icon: '🤺',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'person fencing',
  },
  {
    code: [''],
    icon: '🏇',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'horse racing',
  },
  {
    code: [''],
    icon: '⛷️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'skier',
  },
  {
    code: [''],
    icon: '🏂',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'snowboarder',
  },
  {
    code: [''],
    icon: '🏌️‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man golfing',
  },
  {
    code: [''],
    icon: '🏌️‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman golfing',
  },
  {
    code: [''],
    icon: '🏄‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man surfing',
  },
  {
    code: [''],
    icon: '🏄‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman surfing',
  },
  {
    code: [''],
    icon: '🚣‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man rowing boat',
  },
  {
    code: [''],
    icon: '🚣‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman rowing boat',
  },
  {
    code: [''],
    icon: '🏊‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man swimming',
  },
  {
    code: [''],
    icon: '🏊‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman swimming',
  },
  {
    code: [''],
    icon: '⛹️‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man bouncing ball',
  },
  {
    code: [''],
    icon: '⛹️‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman bouncing ball',
  },
  {
    code: [''],
    icon: '🏋️‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man lifting weights',
  },
  {
    code: [''],
    icon: '🏋️‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman lifting weights',
  },
  {
    code: [''],
    icon: '🚴‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man biking',
  },
  {
    code: [''],
    icon: '🚴‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman biking',
  },
  {
    code: [''],
    icon: '🚵‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man mountain biking',
  },
  {
    code: [''],
    icon: '🚵‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman mountain biking',
  },
  {
    code: [''],
    icon: '🤸‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man cartwheeling',
  },
  {
    code: [''],
    icon: '🤸‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman cartwheeling',
  },
  {
    code: [''],
    icon: '🤼',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'people wrestling',
  },
  {
    code: [''],
    icon: '🤼‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'men wrestling',
  },
  {
    code: [''],
    icon: '🤼‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'women wrestling',
  },
  {
    code: [''],
    icon: '🤽‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man playing water polo',
  },
  {
    code: [''],
    icon: '🤽‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman playing water polo',
  },
  {
    code: [''],
    icon: '🤾‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man playing handball',
  },
  {
    code: [''],
    icon: '🤾‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman playing handball',
  },
  {
    code: [''],
    icon: '🤹‍♂️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'man juggling',
  },
  {
    code: [''],
    icon: '🤹‍♀️',
    parent_cat: 'people',
    child_cat: 'sport',
    short_name: 'woman juggling',
  },
  {
    code: [''],
    icon: '🧘‍♂️',
    parent_cat: 'people',
    child_cat: 'resting',
    short_name: 'man in lotus position',
  },
  {
    code: [''],
    icon: '🧘‍♀️',
    parent_cat: 'people',
    child_cat: 'resting',
    short_name: 'woman in lotus position',
  },
  {
    code: [''],
    icon: '🛀',
    parent_cat: 'people',
    child_cat: 'resting',
    short_name: 'person taking bath',
  },
  {
    code: [''],
    icon: '🛌',
    parent_cat: 'people',
    child_cat: 'resting',
    short_name: 'person in bed',
  },
];
